hobbytrip/hobbytrip

- src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/contorller/EmojiController.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/domain/Emoji.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/dto/EmojiDto.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/dto/request/EmojiCreateRequest.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/dto/request/EmojiDeleteRequest.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/dto/response/EmojiCreateResponse.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/dto/response/EmojiDeleteResponse.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/repository/EmojiRepository.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/service/EmojiService.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/controller/ServerMessageController.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/dto/ServerMessageDto.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/repository/ServerMessageRepository.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/server/service/ServerMessageService.java
- src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/KafkaProducerConfig.java
- src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/consumer/EmojiChatConsumerConfig.java
- src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/consumer/ServerChatConsumerConfig.java
- src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/KafkaConsumer.java
- src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/KafkaProducer.java
> feat: 서버 채팅, 댓글 조회 api와 이모지 생성, 삭제 api 구현

- src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/controller/DirectMessageController.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/domain/DirectMessage.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/dto/DirectMessageDto.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/dto/request/DirectMessageCreateRequest.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/dto/request/DirectMessageDeleteRequest.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/dto/request/DirectMessageModifyRequest.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/dto/response/DirectMessageCreateResponse.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/dto/response/DirectMessageDeleteResponse.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/dto/response/DirectMessageModifyResponse.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/repository/DirectMessageRepository.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/dm/service/DirectMessageService.java
- src/backend/chat-service/src/main/java/capstone/chatservice/domain/emoji/repository/EmojiRepository.java
- src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/KafkaProducerConfig.java
- src/backend/chat-service/src/main/java/capstone/chatservice/global/config/kafka/consumer/DirectChatConsumerConfig.java
- src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/KafkaConsumer.java
- src/backend/chat-service/src/main/java/capstone/chatservice/infra/kafka/KafkaProducer.java
> feat: DM CRUD api, DM producer, consumer 구현

- src/backend/community-service/build.gradle
- src/backend/community-service/src/main/java/capstone/communityservice/domain/category/controller/CategoryCommandController.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/category/dto/CategoryCreateRequestDto.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/category/dto/CategoryDeleteRequestDto.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/category/dto/CategoryResponseDto.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/category/dto/CategoryUpdateRequestDto.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/category/service/CategoryCommandService.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/channel/controller/CategoryController.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/channel/controller/ChannelCommandController.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/channel/dto/ChannelCreateRequestDto.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/channel/dto/ChannelDeleteRequestDto.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/channel/dto/ChannelResponseDto.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/channel/dto/ChannelUpdateRequestDto.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/channel/entity/Channel.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/channel/service/ChannelCommandService.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/dm/controller/DmCommandController.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/dm/dto/DmDeleteProfileRequestDto.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/dm/dto/DmResponseDto.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/dm/dto/DmUpdateProfileRequestDto.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/dm/entity/Dm.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/dm/service/DmCommandService.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/server/controller/ServerCommandController.java
- src/backend/community-service/src/main/java/capstone/communityservice/domain/server/service/ServerCommandService.java
- src/backend/community-service/src/main/java/capstone/communityservice/global/config/KafkaProducerConfig.java
- src/backend/community-service/src/main/java/capstone/communityservice/global/config/KafkaTopicConfig.java
> feat: 카테고리 CUD, DM 프로필 이미지, 채널 CUD, 카프카 설정

- src/backend/user-service/build.gradle
- src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/controller/ProfileController.java
- src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/dto/request/ProfileImageRequest.java
- src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/dto/request/ProfileNicknameRequest.java
- src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/dto/response/ProfileImageResponse.java
- src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/exception/S3Exception.java
- src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/service/ProfileService.java
- src/backend/user-service/src/main/java/com/capstone/userservice/domain/profile/service/S3ImageService.java
- src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/controller/AuthController.java
- src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/controller/UserController.java
- src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/dto/TokenRequest.java
- src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/dto/UserDeleteRequest.java
- src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/dto/UserRequest.java
- src/backend/user-service/src/main/java/com/capstone/userservice/domain/user/entity/User.java
- src/backend/user-service/src/main/java/com/capstone/userservice/global/common/entity/RefreshToken.java
- src/backend/user-service/src/main/java/com/capstone/userservice/global/config/S3Config.java
- src/backend/user-service/src/main/java/com/capstone/userservice/global/exception/Code.java
**🙆🏻‍♀️ Related Issue**
[[BE] 유저 서비스 프로젝트 초기 설정 및 기능 구현](https://github.com/hobbytrip/hobbytrip/issues/22)
> feat: refreshToken redis 구현

- src/frontend/src/App.jsx
- src/frontend/src/components/MenuView/ExitHeader/ExitHeader.jsx
- src/frontend/src/components/MenuView/ExitHeader/ExitHeader.module.css
- src/frontend/src/components/MenuView/Menu/Menu.jsx
- src/frontend/src/components/MenuView/Menu/Menu.module.css
- src/frontend/src/pages/MenuView/MenuView.jsx
- src/frontend/src/pages/MenuView/MenuView.module.css
MenuView 구현
- 유저, 메뉴 구현
- 아래 쪽의 로고는 임의로 높이를 조금 조정했습니다
- 지난 번 PR에서 App.jsx의 내용을 삭제해버려서 다시 추가했습니다
> feat: MenuView 구현 

- src/frontend/src/actions/useUserStore.js
- src/frontend/src/pages/UserProfileView/UserProfileView.jsx
refactor: 사용자 정보 조회 함수 추가 및 코드 리팩토링
전역적으로 사용자 정보를 관리하기 위해 사용자 정보를 get 해오는 함수를 store에 추가하였습니다.
> refactor: 사용자 정보 조회 함수 추가 및 코드 리팩토링

- src/backend/sig-service/Dockerfile
- src/backend/sig-service/build.gradle
- src/backend/sig-service/src/main/java/capstone/sigservice/Kafka/KafkaProducer.java
- src/backend/sig-service/src/main/java/capstone/sigservice/SigServiceApplication.java
- src/backend/sig-service/src/main/java/capstone/sigservice/config/JasyptConfig.java
- src/backend/sig-service/src/main/java/capstone/sigservice/config/KafkaProducerConfig.java
- src/backend/sig-service/src/main/java/capstone/sigservice/config/KafkaTopicConfig.java
- src/backend/sig-service/src/main/java/capstone/sigservice/config/WebMvcConfig.java
- src/backend/sig-service/src/main/java/capstone/sigservice/controller/CommunitySessionController.java
- src/backend/sig-service/src/main/java/capstone/sigservice/dto/UserLocationEventDto.java
- src/backend/sig-service/src/main/java/capstone/sigservice/service/CommunitySessionService.java
- src/backend/sig-service/src/test/java/capstone/sigservice/SigServiceApplicationTests.java
> 유저입장시 상태관리서버에 유저위치전송

- src/frontend/src/components/MediaView/MediaCall/MediaCall.jsx
- src/frontend/src/pages/MainView/MainView.jsx
- src/frontend/src/utils/API/API.js
#26 
API로 URL 설정, userId를 userStore에서 가져오는 방식으로 리팩토링 했습니다.
> refactor:  미디어 리팩토링

- src/frontend/src/App.jsx
- src/frontend/src/actions/useAuthStore.js
- src/frontend/src/actions/useUserStore.js
- src/frontend/src/components/LoginForm/LoginForm.jsx
- src/frontend/src/components/Modal/ForumModal/CreateForumModal/ForumModal.jsx
- src/frontend/src/components/Modal/ForumModal/CreateForumModal/ForumModal.module.css
- src/frontend/src/components/Modal/ServerModal/Category/CreateCategory/CreateCategory.jsx
- src/frontend/src/components/Modal/ServerModal/CreateServer/CreateServer.jsx
- src/frontend/src/components/RegForm/RegForm.jsx
- src/frontend/src/hooks/User/login.js
- src/frontend/src/pages/Chat/ForumRoom/ForumRoom.jsx
- src/frontend/src/pages/Chat/ForumRoom/ForumRoom.module.css
- src/frontend/src/pages/MainView/MainView.jsx
- src/frontend/src/utils/API/TEST_API.js
- src/frontend/src/utils/axiosInstance.js
- src/frontend/src/utils/instance.js
#93 #98 
회원가입, 로그인 후 토큰을 잘 받아오는지, 유저의 정보를 잘 저장하는지 확인했습니다.
유저 관리 파일에 변동사항이 있으니 확인 부탁드려요. 이전과 다르게 userId를 사용하고 싶다면 `const {userId} = useUserStore();` 이렇게 가져오면 됩니다.!
그리고 추후에 유저 프로필 사진도 추가해서 PR 올리겠습니다.
localStorage에 토큰을 저장하는 방식을 사용했기 때문에, 만약 로그인/회원가입부터 테스트한다면 `개발자도구-응용프로그램-로컬저장소`에 토큰이 있는지 확인하고, 만약 있다면 지워주시고 진행하시면 됩니다.
> feat: 토큰 인증 확인 및 포럼 생성 기능 구현

- src/frontend/src/actions/useServerStore.js
- src/frontend/src/components/MainView/MyPlanet/MyPlanet.jsx
- src/frontend/src/components/MainView/MyPlanet/MyPlanet.module.css
- src/frontend/src/components/Modal/ChatModal/ChatRoomInfo/ChatRoomInfo.jsx
- src/frontend/src/components/Modal/ServerModal/Servers/JoinServer/JoinServer.jsx
- src/frontend/src/components/ServerView/CategoryList/CategoryList.module.css
- src/frontend/src/components/ServerView/SeverSetting/ServerSetting.jsx
- src/frontend/src/components/ServerView/SeverSetting/ServerSetting.module.css
- src/frontend/src/pages/ServerView/CategoryView/CategoryView.jsx
- src/frontend/src/utils/axiosInstance.js
#72 
기존에 안 되던 서버 수정 버그와 링크로 가입 시 되지 않던 버그를 해결했습니다.
더불어 행성 접속 시에 가끔 서버 정보를 불러오지 못하던 버그도 해결했습니다.
서버 수정 시 이미지 O -> 이미지 X 경우 이미지 삭제는 해결하지 못 했으나 빠르게 고칠 예정입니다.
> fix: 서버 수정, 링크 접속 버그 해결

- src/frontend/src/actions/useServerStore.js
- src/frontend/src/components/MainView/MyPlanet/MyPlanet.jsx
- src/frontend/src/components/MediaView/MediaCall/MediaCall.jsx
- src/frontend/src/components/Modal/ServerModal/Servers/CreateServer/CreateServer.jsx
- src/frontend/src/components/ServerView/CategoryList/CategoryList.jsx
- src/frontend/src/components/ServerView/SeverSetting/ServerSetting.jsx
- src/frontend/src/pages/MainView/MainView.jsx
- src/frontend/src/utils/API/API.js
#26 
미디어 연결 시의 나던 버그들을 수정했습니다. 기존 FE/server 브랜치에서 작업해버려서 이쪽으로 PR 날렸습니다...
> fix: 미디어 연결 버그 수정 완료

- src/frontend/src/actions/useChatStore.js
- src/frontend/src/actions/useWebSocketStore.js
- src/frontend/src/components/LoginForm/LoginForm.jsx
- src/frontend/src/components/MainView/MyPlanet/MyPlanet.jsx
- src/frontend/src/components/Modal/ChatModal/CreateChatModal/ChatModal.jsx
- src/frontend/src/components/Modal/ChatModal/CreateChatModal/MessageSender/MessageSender.jsx
- src/frontend/src/components/Modal/ServerModal/Servers/CreateServer/CreateServer.jsx
- src/frontend/src/components/RegForm/RegForm.jsx
- src/frontend/src/pages/Chat/ChatRoom/ChatRoom.jsx
- src/frontend/src/pages/Chat/ChatRoom/ChatRoom.module.css
- src/frontend/src/pages/MainView/MainView.jsx
> refactor: 채팅방 구독

- src/backend/sig-service/Dockerfile
- src/backend/sig-service/src/main/java/capstone/sigservice/config/WebMvcConfig.java
- src/backend/sig-service/src/main/java/capstone/sigservice/controller/CommunitySessionController.java
- src/backend/sig-service/src/main/java/capstone/sigservice/dto/ConnectionDto.java
- src/backend/sig-service/src/main/resources/logback-spring.xml
logback-spring.xml추가 및 간단한 수정을 했습니다
> refactor: logback-spring.xml 추가

- src/frontend/src/App.jsx
- src/frontend/src/actions/useForumListStore.js
- src/frontend/src/components/Modal/ForumModal/ForumList/ForumList.jsx
- src/frontend/src/components/Modal/ForumModal/ForumList/ForumList.module.css
- src/frontend/src/pages/Chat/ForumRoom/ForumRoom.jsx
> feat: 포럼 업데이트 이벤트 추가

- src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/dto/response/WaitingFriendListResponse.java
- src/backend/user-service/src/main/java/com/capstone/userservice/domain/friend/service/FriendshipService.java
- 유저 친구 대기 목록에 친구 이름이 빠져있던 걸 수정하였습니다.
> fix: 유저 친구 수정

- src/frontend/src/components/Modal/FriendModal/AddFriend/AddFriend.module.css
- src/frontend/src/components/Modal/FriendModal/FriendList/FriendList.jsx
- src/frontend/src/components/Modal/FriendModal/MyFriend/MyFriend.jsx
- src/frontend/src/utils/API/API.js
#115 알림 관련한 이슈로 에러나는 부분 주석처리하고 PR 올립니다
우선 친구 서비스 사용하지 않는 DM 구현 예정입니다.
> bug: 친구 요청 및 수락 거절 이슈

- src/frontend/src/App.jsx
- src/frontend/src/components/Modal/ChatModal/ChatRoomInfo/ChatRoomInfo.jsx
- src/frontend/src/components/ServerView/FriendsList/FriendsList.jsx
- src/frontend/src/components/ServerView/FriendsList/FriendsList.module.css
- src/frontend/src/hooks/useSSE.js
- src/frontend/src/pages/ServerView/FriendsView/FriendsView.jsx
- src/frontend/src/pages/ServerView/FriendsView/FriendsView.module.css
- src/frontend/src/utils/API/API.js
서버의 유저 목록을 표시해주는 뷰 구현했습니다. 더불어 서버 sse도 일단 주석처리 해두었습니다.
> feat: 서버 유저 목록 뷰 구현

- src/frontend/src/components/MenuView/ExitHeader/ExitHeader.jsx
- src/frontend/src/components/MenuView/Menu/Menu.jsx
- src/frontend/src/components/MenuView/Menu/Menu.module.css
- src/frontend/src/components/Modal/FriendModal/FriendList/FriendList.jsx
- src/frontend/src/utils/API/API.js
메뉴 뷰의 기능들을 구현했습니다. 로그아웃은 일단 주석 처리 해뒀습니다.
> feat: 메뉴 뷰 기능 구현

- src/frontend/src/actions/useDmHistoryStore.js
- src/frontend/src/components/TYPE/Community/FriendsList/FriendsList.jsx
- src/frontend/src/components/TYPE/Community/FriendsList/FriendsList.module.css
- src/frontend/src/components/TYPE/DM/DM.jsx
- src/frontend/src/pages/Chat/ChatRoom/ForumChatRoom.jsx
> feat; DM 방 중복 업데이트 버그 해결

- src/frontend/src/actions/usePlantesStore.js
- src/frontend/src/actions/useServerStore.js
- src/frontend/src/components/MainView/MyPlanet/MyPlanet.jsx
- src/frontend/src/components/Modal/FriendModal/MyFriend/MyFriend.module.css
- src/frontend/src/components/Modal/ServerModal/Channel/CreateChannel/CreateChannel.jsx
- src/frontend/src/components/Modal/ServerModal/Servers/CreateServer/CreateServer.jsx
- src/frontend/src/components/Modal/ServerModal/Servers/JoinServer/JoinServer.jsx
- src/frontend/src/components/ServerView/SeverSetting/ServerSetting.jsx
- src/frontend/src/components/TYPE/Community/CategoryList/CategoryList.jsx
- src/frontend/src/components/TYPE/Community/CategoryList/CategoryList.module.css
- src/frontend/src/components/TYPE/Community/Server.jsx
- src/frontend/src/components/TYPE/Community/Server.module.css
- src/frontend/src/components/TYPE/DM/DM.jsx
- src/frontend/src/components/TYPE/DM/DmHistoryList/DmHistoryList.jsx
- src/frontend/src/hooks/useSSE.js
- src/frontend/src/pages/MainView/MainView.jsx
- src/frontend/src/pages/MainView/MainView.module.css
서버에 초대링크로 가입할 때 참여 모달이 안 꺼지고 바로 화면 이동이 안 되는 오류를 수정했습니다. 더불어 서버 CUD가 데탑 버전에서 바로 반영되지 않는 점들도 수정하고, 서버 목록이 화면 밖으로 넘어가지 않게끔 수정했습니다. 데탑 버전에서 초대 링크, 세팅 화면으로 가는 아이콘도 추가했습니다.
> fix: 서버 join 버그 해결

- src/frontend/src/components/TYPE/DM/DM.jsx
- src/frontend/src/components/TYPE/DM/DmHistoryList/DmHistoryList.jsx
[refactor] #159 - userID update
> refactor: userID update

- src/backend/notification-service/src/main/java/com/capstone/notificationservice/global/config/kafka/FriendAlarmTopicConfig.java
- src/backend/notification-service/src/main/java/com/capstone/notificationservice/global/config/kafka/KafkaTopicConfig.java
- 유저 친구 요청 알림 컨슈머 설정
- 서브모듈 설정
> feat: 서브모듈 수정 및 컨슈머 설정

- src/backend/notification-service/src/main/java/com/capstone/notificationservice/domain/dm/service/DmNotificationService.java
- src/backend/notification-service/src/main/java/com/capstone/notificationservice/domain/server/service/EmitterServerNotificationService.java
- src/backend/notification-service/src/main/java/com/capstone/notificationservice/domain/user/controller/UserNotificationController.java
- src/backend/notification-service/src/main/java/com/capstone/notificationservice/domain/user/dto/UserNotificationDto.java
- src/backend/notification-service/src/main/java/com/capstone/notificationservice/domain/user/entity/User.java
- src/backend/notification-service/src/main/java/com/capstone/notificationservice/domain/user/entity/UserNotification.java
- src/backend/notification-service/src/main/java/com/capstone/notificationservice/domain/user/exception/UserException.java
- src/backend/notification-service/src/main/java/com/capstone/notificationservice/domain/user/repository/UserNotificationRepository.java
- src/backend/notification-service/src/main/java/com/capstone/notificationservice/domain/user/repository/UserRepository.java
- src/backend/notification-service/src/main/java/com/capstone/notificationservice/domain/user/service/UserNotificationService.java
- src/backend/notification-service/src/main/java/com/capstone/notificationservice/domain/user/service/UserService.java
- src/backend/notification-service/src/main/java/com/capstone/notificationservice/global/config/kafka/FriendAlarmConsumerConfig.java
- 유저 친구 요청시 발생하는 알림 이벤트 처리
- 관련 서비스, 컨슈머 등 설정
> feat: 유저 친구 요청 알림 구현

- src/frontend/src/actions/useChatStore.js
- src/frontend/src/actions/useServerStore.js
- src/frontend/src/components/Common/ChatRoom/ChatRoom.module.css
- src/frontend/src/components/MainView/MyPlanet/MyPlanet.jsx
- src/frontend/src/components/RegForm/RegForm.jsx
- src/frontend/src/components/TYPE/Community/CommunityChatRoom.jsx
- src/frontend/src/components/TYPE/Community/Server.jsx
- src/frontend/src/hooks/useFetchServer.js
- src/frontend/src/pages/MainView/MainView.jsx
- src/frontend/src/utils/User/getUser.js
- src/frontend/src/utils/axiosInstance.js
행성 아이콘 클릭시 해당 서버의 정보를 fetch 하고, 이를 store에 업데이트 되지 않는 문제를 해결했습니다.
fetch하는 부분을 분리 후 사용하는 부분에서, 비동기 처리 과정에서 발생한 버그입니다.
> fix: 서버 정보 조회 후 store 정보 업데이트 안되는 오류 해결
